language: python
python: '3.4'
env:
  - PORT=5000
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -e .
  - pip install -r test_requirements.txt
  - npm install -g browserify
  - npm install -g mocha
  - (cd static/js && npm --python=/usr/bin/python2.7 install)
before_script:
  - (cd static/js && browserify drippies.js -o app.js)
  - honcho start 2>&1 > /dev/null &
  - sleep 3
script:
  - py.test
  - (cd static/js && mocha)
deploy:
  provider: heroku
  api_key:
    secure: Nq9LZfinaQBlENCsmwSdr1W5pv4zkbRn30Hh4ldS/Qb/cujewgNRnc+E+5W4IE03y/3nDpSFX1DxmFCvWfUYPxfmZrrvecPDDXqPwFhsxBZKxjU3yz8QNC/QgX08UgL2ZHiL6vMjqGthg0Uq3AONRmTyLQLNm3sQJT+DW+EasgU=
  app: drippies
  skip_cleanup: true
  on:
    repo: grampajoe/drippies
    branch: master
