language: python
python: '3.4'
env:
  global:
    - PORT=5000
    - secure: UwRsa+ZV1+PsBsqeHdAYFRU2mFqege7By82Z4aqQ8EzXDj0g1Sb9vJIUP233xn5SdQ0t8kK+QN63KC+CsVuxb1OEjClvgXZ1Nt3yPo/cj69MYh0hWoq0RnxLo6LJwqYGIwg53twYt+EgHNeEfyu34pwTKNRZdbgSnQo/B0fM1GA=
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -e .
  - pip install -r test_requirements.txt
  - npm install -g browserify mocha uglify-js
  - (cd js && npm --python=/usr/bin/python2.7 install)
before_script:
  - (cd js && npm run-script build)
  - honcho start 2>&1 > honcho.log &
  - sleep 3
script:
  - py.test
  - (cd js && npm test)
after_script:
  - pkill -SIGINT -f gunicorn
  - cat honcho.log
deploy:
  provider: heroku
  api_key:
    secure: Nq9LZfinaQBlENCsmwSdr1W5pv4zkbRn30Hh4ldS/Qb/cujewgNRnc+E+5W4IE03y/3nDpSFX1DxmFCvWfUYPxfmZrrvecPDDXqPwFhsxBZKxjU3yz8QNC/QgX08UgL2ZHiL6vMjqGthg0Uq3AONRmTyLQLNm3sQJT+DW+EasgU=
  app: drippies
  skip_cleanup: true
  on:
    repo: grampajoe/drippies
    branch: master
