language: python
python: '3.4'
install:
- pip install -e .
- pip install pytest
script: py.test
deploy:
  provider: heroku
  api_key:
    secure: Nq9LZfinaQBlENCsmwSdr1W5pv4zkbRn30Hh4ldS/Qb/cujewgNRnc+E+5W4IE03y/3nDpSFX1DxmFCvWfUYPxfmZrrvecPDDXqPwFhsxBZKxjU3yz8QNC/QgX08UgL2ZHiL6vMjqGthg0Uq3AONRmTyLQLNm3sQJT+DW+EasgU=
  app: drippies
  on:
    repo: grampajoe/drippies
    branch: master
