version: 2
jobs:
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt
      - run: py.test
      
